const fackData = [
    {
        id: 0,
        name: 'Biriany',
        image: 'assets/images/biriany/0biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 1,
        name: 'Biriany',
        image: 'assets/images/biriany/1biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 2,
        name: 'Biriany',
        image: 'assets/images/biriany/2biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 3,
        name: 'Biriany',
        image: 'assets/images/biriany/3biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 4,
        name: 'Biriany',
        image: 'assets/images/biriany/4biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 5,
        name: 'Biriany',
        image: 'assets/images/biriany/5biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 6,
        name: 'Biriany',
        image: 'assets/images/biriany/6biriany.jpeg',
        category: 'briany',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 7,
        name: 'Burger',
        image: 'assets/images/burger/0burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 8,
        name: 'Burger',
        image: 'assets/images/burger/1burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 9,
        name: 'Burger',
        image: 'assets/images/burger/2burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 10,
        name: 'Burger',
        image: 'assets/images/burger/3burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 11,
        name: 'Burger',
        image: 'assets/images/burger/4burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 12,
        name: 'Burger',
        image: 'assets/images/burger/5burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 13,
        name: 'Burger',
        image: 'assets/images/burger/6burger.jpeg',
        category: 'burger',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 14,
        name: 'Cake',
        image: 'assets/images/cake/0cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 15,
        name: 'Cake',
        image: 'assets/images/cake/1cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 16,
        name: 'Cake',
        image: 'assets/images/cake/2cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 17,
        name: 'Cake',
        image: 'assets/images/cake/3cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 18,
        name: 'Cake',
        image: 'assets/images/cake/4cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 19,
        name: 'Cake',
        image: 'assets/images/cake/5cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 20,
        name: 'Cake',
        image: 'assets/images/cake/6cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 21,
        name: 'Cake',
        image: 'assets/images/cake/7cake.jpeg',
        category: 'cake',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 22,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/0cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 23,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/1cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 24,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/2cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 25,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/3cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 26,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/4cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 27,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/5cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },
    {
        id: 28,
        name: 'Cotpoti',
        image: 'assets/images/cotpoti/6cotpot.jpeg',
        category: 'cotpoti',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fugit autem repellat facere sequi sint? Esse facilis dicta commodi iste.',
        price: 199,
        rating: 4,
        ratingCount: 230,
    },

]

export default fackData;